name: GM2023
schemes:
  GM2023:
    build:
      targets:
        GM2023: all
        GM2023Tests: [test]
    test:
      gatherCoverageData: true
      coverageTargets:
        - GM2023
      targets: 
        - GM2023Tests
      commandLineArguments:
        "-isRunningUnitTests YES": true
options:
  bundleIdPrefix: uk.co.cerihughes
  deploymentTarget:
    iOS: "16.0"
packages:
  Realm:
    url: https://github.com/realm/realm-swift
    majorVersion: 10.0.0
  Madog:
    url: https://github.com/cerihughes/Madog
    majorVersion: 7.0.0
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    majorVersion: 5.0.0
targets:
  GM2023:
    type: application
    platform: iOS
    settings:
      INFOPLIST_FILE: Source/Secret.plist
      DEVELOPMENT_TEAM: Y56955G4Q8
    sources:
      - path: GM2023
      - path: Source
        buildPhase: none
        includes:
          - "Info.plist"
          - "Secret.plist"
    dependencies:
      - package: Realm
        product: RealmSwift
      - package: Madog
      - package: SnapKit
    postCompileScripts:
      - script: $PROJECT_DIR/ios-tools/copy-plist.sh
        name: Copy Plist
        basedOnDependencyAnalysis: false
      - script: export PATH="/opt/homebrew/bin:$PATH";swiftlint
        name: Swift Lint
        basedOnDependencyAnalysis: false
  GM2023Tests:
    type: bundle.unit-test
    platform: iOS
    sources: GM2023Tests
    dependencies:
      - target: GM2023
